[workspace]

members = [
    "grok",
    "cat",
    "document",
    "indexed_file",
    "play",          # a playground to test rust functionality.  Should we move this from `members` to `exclude`?
    "tac",
    "tools",
]
resolver = "2"