[package]
name = "tools"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pico-args = "0.4.2"
indexed_file = { path = "../indexed_file" }
document = { path = "../document" }
log = "0.4"